export const Add_Customer = "Add_Customer"
export const Get_Customer = "Get_Customer"
export const Edit_Customer = "Edit_Customer"
export const Add_Product = "Add_Product"
export const Get_Product = "Get_Product"